server:
  port: 8031

spring:
  application:
    name: microservice-hystrix-turbine

  rabbitmq:
    host: 122.9.61.197
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
