debug: true

# 配置 SSL
server:
    port: 8443
    ssl:
      key-store: classpath:server.keystore
      key-store-password: 123456
      key-alias: localhost

spring:

    datasource:
        name: test
        url: jdbc:postgresql://localhost:5432/shiro
        username: postgres
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.com.hason.entity
    configuration:
        # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射
        map-underscore-to-camel-case: true
#    mybatis.config：mybatis-config.xml配置文件的路径
#    mybatis.typeHandlersPackage：扫描typeHandlers的包
#    mybatis.checkConfigLocation：检查配置文件是否存在
#    mybatis.executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE