server:
  port: 8000

eureka:
  client:
    serviceUrl:
      # 服务注册（无需密码）
      defaultZone: http://localhost:8761/eureka/
      # 服务注册（需要密码），格式：http://username:password@EUREKA_HOST:EUREKA_PORT/eureka/
#      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    # 将自己的IP注册到 Eureka Server，false 表示注册微服务所在操作系统的 hostname 到 Eureka Server
    prefer-ip-address: true

spring:
  application:
    name: microservice-provider-user   # 注册到 Eureka Server 上的应用名称
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                     # 指定数据源
    platform: postgresql          # 指定数据源类型
    schema: classpath:schema.sql  # 指定建表脚本
    data: classpath:data.sql      # 指定数据脚本

    name: test
    url: jdbc:postgresql://localhost:5432/spring-cloud
    username: postgres
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver

# 配置日志级别，让 hibernate 打印执行的SQL
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
debug: true

## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
