server:
  port: 8080
spring:
  application:
    name: microservice-config-server-eureka
  rabbitmq:
    host: 122.9.61.197
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      trace:
        enabled: true   # 开启 Cloud Bus 的跟踪
    config:
      server:
        git:
          # 配置 Git 仓库的地址
          uri: https://github.com/HasonHuang/spring-cloud-config-server-repo
          # Git 仓库账号
          #username: HasonHuang
          # Git 仓库密码
          #password: hason2012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/