server:
  port: 8031

spring:
  application:
    name: microservice-hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

turbine:
  # 监控的微服务
  app-config: microservice-consumer-moive,microservice-consumer-moive-feign-hystrix-fallback-stream
  cluster-name-expression: "'default'"


