server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                     # 指定数据源
    platform: postgresql          # 指定数据源类型
    schema: classpath:schema.sql  # 指定建表脚本
    data: classpath:data.sql      # 指定数据脚本

    name: test
    url: jdbc:postgresql://localhost:5432/spring-cloud
    username: postgres
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver

# 配置日志级别，让 hibernate 打印执行的SQL
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
debug: true

## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
