server:
  port: 9000

spring:
  application:
    name: tcc-account

  # 数据库配置
  datasource:
    url: jdbc:postgresql://localhost:5432/tcc_user
    username: postgres
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver

    initialize: false             # 是否初始化
    platform: postgresql          # 指定数据源类型
    schema: classpath:schema.sql  # 指定建表脚本
#    data: classpath:data.sql      # 指定数据脚本

    # 配置 TCC框架使用的数据源
    tcc:
      url: jdbc:postgresql://localhost:5432/tcc
      username: postgres
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  # 配置 RabbitMQ 消息队列：队列配置见底部
#  rabbitmq:
#    host: 122.9.61.197
#    port: 5672
#    username: admin
#    password: admin

# 配置服务注册
eureka:
  instance:
    # 将自己的IP注册到 Eureka Server，false 表示注册微服务所在操作系统的 hostname 到 Eureka Server
    prefer-ip-address: true
  client:
    serviceUrl:
      # 服务注册（无需密码）
      defaultZone: http://localhost:8761/eureka
      # 服务注册（需要密码），格式：http://username:password@EUREKA_HOST:EUREKA_PORT/eureka/
#      defaultZone: http://user:password123@localhost:8761/eureka/

# 禁用 Feign 的 Hystrix，不使用断路器
feign:
  hystrix:
    enabled: false

# 配置日志级别，让 hibernate 打印执行的SQL
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
debug: true

## 启用 Actuator 后，访问 host:port/info 显示以下信息；占位符引用 Maven 配置信息
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
