debug: true
server:
  port: 8010

logging:
  level:
    # 将 Feign 接口的日志级别设置成 DEBUG, 因为 Feign 的 Logger.LEVEL 支对 DEBUG 作出响应
    com.hason.feign.UserFeignClient: DEBUG

spring:
  application:
    name: microservice-consumer-moive    # 注册到 Eureka Server 上的应用名称
eureka:
  client:
    service-url:
      # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 将自己的IP注册到 Eureka Server，false 表示注册微服务所在操作系统的 hostname 到 Eureka Server
    prefer-ip-address: true