server:
  port: 8080
encrypt:
  key-store:
    location: classpath:/server.jks  # jks文件路径
    password: letmein                # storepass
    alias: mytestkey                 # alias
    secret: changeme                 # keypass
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # 配置 Git 仓库的地址
          uri: https://github.com/HasonHuang/spring-cloud-config-server-repo
          # Git 仓库账号
          #username: HasonHuang
          # Git 仓库密码
          #password: hason2012
