spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  # 指定profile=peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    # 启用profile=peer1时，指定主机名是 peer1
    hostname: peer1
  client:
#    registerWithEureka: false   # 是否将自己注册到 Eureka Server
#    fetchRegistry: false        # 是否从 Eureka Server 获取注册信息
    serviceUrl:
      # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:8761/eureka/
      # 将自己注册到 peer2 这个 Eureka 上面去
      defaultZone: http://peer2:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/