server:
  port: 8761
spring:
  application:
    name: ms-discovery-eureka
eureka:
  instance:
    hostname: discovery-1
  client:
    serviceUrl:
      # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:8761/eureka